export const GET_LIST_COIN_ITEM = 'GET_LIST_COIN_ITEM';
export const GET_LIST_COIN_ITEM_SUCCESS = 'GET_LIST_COIN_ITEM_SUCCESS';
export const GET_LIST_COIN_ITEM_FAIL = 'GET_LIST_COIN_ITEM_FAIL';

export const GET_LIST_TOPUP_ITEM = 'GET_LIST_TOPUP_ITEM';
export const GET_LIST_TOPUP_ITEM_SUCCESS = 'GET_LIST_TOPUP_ITEM_SUCCESS';
export const GET_LIST_TOPUP_ITEM_FAIL = 'GET_LIST_TOPUP_ITEM_FAIL';

export const GET_LIST_COIN_PROMOTINO_ITEM = 'GET_LIST_COIN_PROMOTINO_ITEM';
export const GET_LIST_COIN_PROMOTINO_ITEM_SUCCESS = 'GET_LIST_COIN_PROMOTINO_ITEM_SUCCESS';
export const GET_LIST_COIN_PROMOTINO_ITEM_FAIL = 'GET_LIST_COIN_PROMOTINO_ITEM_FAIL';
// update, create promotion
export const CHANGE_PROMOTINO_ITEM = 'CHANGE_PROMOTINO_ITEM';
export const CHANGE_PROMOTINO_ITEM_SUCCESS = 'CHANGE_PROMOTINO_ITEM_SUCCESS';
export const CHANGE_PROMOTINO_ITEM_FAIL = 'CHANGE_PROMOTINO_ITEM_FAIL';

