
export const GET_LIST_PAYMENT_ITEM = 'GET_LIST_PAYMENT_ITEM';
export const GET_LIST_PAYMENT_ITEM_SUCCESS = 'GET_LIST_PAYMENT_ITEM_SUCCESS';
export const GET_LIST_PAYMENT_ITEM_FAIL = 'GET_LIST_PAYMENT_ITEM_FAIL';
