export const GET_LIST_TOPUP_ITEM = 'GET_LIST_TOPUP_ITEM';
export const GET_LIST_TOPUP_ITEM_SUCCESS = 'GET_LIST_TOPUP_ITEM_SUCCESS';
export const GET_LIST_TOPUP_ITEM_FAIL = 'GET_LIST_TOPUP_ITEM_FAIL';
export const GET_LIST_COIN_PROMOTINO_ITEM = 'GET_LIST_COIN_PROMOTINO_ITEM';
export const GET_LIST_COIN_PROMOTINO_ITEM_SUCCESS = 'GET_LIST_COIN_PROMOTINO_ITEM_SUCCESS';
export const GET_LIST_COIN_PROMOTINO_ITEM_FAIL = 'GET_LIST_COIN_PROMOTINO_ITEM_FAIL';
